<?php

namespace AppBundle\Repository;

/**
 * LogNozirohRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogNozirohRepository extends \Doctrine\ORM\EntityRepository
{
}
